use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum ServiceCategory {
    ShiftCoverage,
    CallCoverage,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Service {
    pub id: String,
    pub name: String,
    pub category: ServiceCategory,
    pub is_weekend: bool,
    pub is_night_call: bool,
    pub bundled_with: Option<String>,
    pub description: String,
}

pub fn default_services() -> Vec<Service> {
    vec![
        Service {
            id: "am_readout".into(),
            name: "AM Read out".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: Some("msk".into()),
            description: "Morning checkout readout".into(),
        },
        Service {
            id: "abd".into(),
            name: "ABD".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: None,
            description: "Abdominal imaging".into(),
        },
        Service {
            id: "msk".into(),
            name: "MSK".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: Some("am_readout".into()),
            description: "Musculoskeletal reading room".into(),
        },
        Service {
            id: "us".into(),
            name: "US".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: None,
            description: "Ultrasound service".into(),
        },
        Service {
            id: "peds".into(),
            name: "PEDS".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: None,
            description: "Pediatric radiology".into(),
        },
        Service {
            id: "nm".into(),
            name: "NM".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: None,
            description: "Nuclear Medicine".into(),
        },
        Service {
            id: "chest".into(),
            name: "CHEST".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: None,
            description: "Chest & Thoracic".into(),
        },
        Service {
            id: "er".into(),
            name: "ER".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: None,
            description: "Emergency room coverage".into(),
        },
        Service {
            id: "mammo".into(),
            name: "MAMMO".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: None,
            description: "Mammography".into(),
        },
        Service {
            id: "lunch".into(),
            name: "LUNCH 12-1".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: None,
            description: "Midday relief cover".into(),
        },
        Service {
            id: "float".into(),
            name: "FLOAT".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: None,
            description: "Float attending".into(),
        },
        Service {
            id: "evening".into(),
            name: "EVENING".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: None,
            description: "Evening checkout".into(),
        },
        Service {
            id: "general".into(),
            name: "GENERAL".into(),
            category: ServiceCategory::ShiftCoverage,
            is_weekend: false,
            is_night_call: false,
            bundled_with: None,
            description: "General radiology".into(),
        },
        // Call Services
        Service {
            id: "nm_call".into(),
            name: "NM CALL".into(),
            category: ServiceCategory::CallCoverage,
            is_weekend: true,
            is_night_call: true,
            bundled_with: None,
            description: "Nuclear Med call".into(),
        },
        Service {
            id: "peds_call".into(),
            name: "PEDS CALL".into(),
            category: ServiceCategory::CallCoverage,
            is_weekend: true,
            is_night_call: true,
            bundled_with: None,
            description: "Pediatric call".into(),
        },
        Service {
            id: "cardiac_call".into(),
            name: "CARDIAC CALL".into(),
            category: ServiceCategory::CallCoverage,
            is_weekend: true,
            is_night_call: true,
            bundled_with: None,
            description: "Cardiac CT/MRI call".into(),
        },
        Service {
            id: "msk_mri_call".into(),
            name: "MSK MRI CALL".into(),
            category: ServiceCategory::CallCoverage,
            is_weekend: true,
            is_night_call: true,
            bundled_with: None,
            description: "MSK MRI weekend call".into(),
        },
        Service {
            id: "trauma_call".into(),
            name: "TRAUMA CALL".into(),
            category: ServiceCategory::CallCoverage,
            is_weekend: true,
            is_night_call: true,
            bundled_with: None,
            description: "Trauma emergency call".into(),
        },
    ]
}
